### ISSUE TITLE
Not working with newer SHAP versions

### ISSUE THREAD

**Issue by claudiacdlira** [nubank/fklearn#109]
### Problem description
When running lgbm with `apply_shap=True`, it throws a `ValueError`. Apparently there was a change on Shap's output (to a list of ndarray) on its newer versions. (https://github.com/slundberg/shap/blob/master/shap/explainers/tree.py#L194)

### Issue location
fklearn/training/classification.py on lgbm_classification_learner

### Expected behavior
`f(df, apply_shap=True)` used to return the original dataframe with a column "shap_values" with an array as value

### Possible solutions
Adapt lgbm_classication_learner to newer (>=0.31.0) shap versions

**Comment by dieggoluis** [comment]
I think taking `shap_values[1]` instead of just `shap_values` (e.g here https://github.com/nubank/fklearn/blob/d983f4fe89062e171ed308beb77b5b9eb905ca8c/src/fklearn/training/classification.py#L204) should solve the problem for binary classification.

**Comment by tatasz** [comment]
And also `explainer.expected_value[1]` in here.

https://github.com/nubank/fklearn/blob/d983f4fe89062e171ed308beb77b5b9eb905ca8c/src/fklearn/training/classification.py#L192

Those two tweaks are enough to fix binary classification.
