### ISSUE TITLE
Support for ONNX

### ISSUE THREAD

**Issue by mglowacki100** [nubank/fklearn#114]
### Describe the feature and the current state.
_Support for onnx format: https://github.com/onnx in similar form like for sklearn._

### Will this change a current behavior? How?
_No, but it will increase interoperability for some tools that support onnx but not fklearn e.g. mlflow_

**Comment by caique-lima** [comment]
@mglowacki100 I'm not sure if we should direct support ONNX as it's more related to the way we represent models, and we choose to remove this responsibility from fklearn. But we can take a look of how can we make pipelines more friendly to other frameworks, and maybe even write something to take care of make this integration fklearn <> ONNX more easy(maybe another project?)

By the docs/code isn't fully clear but in our day-to-day ops, we represent models in two ways:
- Saving the predict_fn that the pipelines output as a pickle(what restrict which types of models we can deploy)
- Using the `_fkml_` to describe the pipe and "translate" it to other languages/frameworks https://github.com/nubank/fklearn/blob/master/src/fklearn/training/pipeline.py#L96

But sounds as a good opportunity to make it easier to deploy the trained models

**Comment by mglowacki100** [comment]
Thanks! Btw. do you use standard `pickle` or pickle from `dill`? AFAIK `dill` is slower but allows to pickle more exotic things.
