### ISSUE TITLE
Output encoded values into a new column

### ISSUE THREAD

**Issue by tatasz** [nubank/fklearn#116]
### Describe the feature and the current state.
Currently, most of fklearn transformations (such as `transformation.target_categorizer`, `transformation.truncate_categorical`, `transformation.rank_categorical`) replace the original values by the encoded values.

### Will this change a current behavior? How?
However, for a series of reasons (such as preserving the original value, or applying multiple encodings to the same feature), one may want to save the encoded values as a different feature, and keep the original column.

It would be useful to add an option to save the encoded feature to a new column.

**Comment by sadikneipp** [comment]
I think you could slice the columns relevant for the encoding and do sth like:

```python

@curry
def add_encoding(df, encoding_fn, relevant_cols):
    slice = df[relevant_cols]
    to_concat = [df, encoding_fn(slice)]
    return pd.concat(to_concat, axis=1)
```

so if you want do to several encodings as a pipeline:

```python
standard_encoding_fns = [sth sthelse]
concat_encoding_fns = [add_encoding(encoding_fn=f, relevant_cols=relevant_cols) for f in standard_encoding_fns]
pipeline_fn = compose(*concat_encoding_fns)
```
