### ISSUE TITLE
Make things like xgboost, lgbm ... extra requirements

### ISSUE THREAD

**Issue by caique-lima** [nubank/fklearn#84]
### Describe the feature and the current state.
Today we choose to install all packages required by fklearn, for development purposes this sounds good, but in production could be better to install only what you need. My idea is to use extra requirements, this way we can have something like:

```
pip install fklearn[xgboost]
```

And we only install the common packages + xgboost, instead of install everything.
We should also include a `fklearn[all]` to install everything

### Will this change a current behavior? How?

Yes, standalone install will not work with most models.

### Additional Information
This needs to be well documented in order to avoid a bad user experience

**Comment by sadikneipp** [comment]
I think that would be great. Specially for the moment where we might want to build sth with large dependencies like torch or tf.

Only drawback I see is that in a production environment the extras would need to be manually specified, right? (No big deal tho)

**Comment by caique-lima** [comment]
@sadikneipp yes, the user will need to write in the requirements the specific version. But I think isn't a big deal given the benefit of a smaller package

**Comment by LucasEstevam** [comment]
what does `standalone install will not work with most models.` mean? If someone only specifies `fklearn==...` as dependency it will install without any extra dependency, is that it?

**Comment by caique-lima** [comment]
@LucasEstevam Exactly, the user will always need to install the actual model it want to run(xgboost, lgbm...). The standalone fklearn will have only the main thing such as the build pipeline, learners that don't depend on a model package

**Comment by gppeixoto** [comment]
Should this issue be closed now that https://github.com/nubank/fklearn/pull/93 was merged? Do we have updated documentation on the [installation guide](https://fklearn.readthedocs.io/en/latest/getting_started.html#installation)?
